apiVersion: copybird.org/v1alpha1
kind: Backup
metadata:
  name: mysqlbackup-sample
spec:
  schedule: "*/1 * * * *"
  storeperiod: "1 month"
  compressionlevel: 2
  database:
    type: "mysql"
    host: "mysql:3306"
    name: "foo"
    user:
      secretKeyRef:
        name: mysqlsecret
        key: user
    password:
      secretKeyRef:
        name: mysqlsecret
        key: password
  storage:
    type: s3
    region: "eu-central-1"
    bucket: "tzununbekov-copybird-backups"
    accesskey:
      secretKeyRef:
        name: awssecret
        key: accesskey
    secretkey:
      secretKeyRef:
        name: awssecret
        key: secretkey
  encryption:
    type: "aesgcm" 
    key:
      secretKeyRef:
        name: copybirdsecret
        key: encryptionkey
  # notifier:
    # - type: stdout
