apiVersion: copybird.org/v1alpha1
kind: Backup
metadata:
  name: mysqlbackup-sample
spec:
  schedule: "*/1 * * * *"
  input:
    # type: "mysqldump"
    # params:
    # - key: "host"
    #   value: "mysql"
    # - key: "port"
    #   value: "3306"
    # - key: "db"
    #   value: "foo"
    # secrets:
    # - secretKeyRef:
    #     name: mysqlsecret
    #     key: user
    # - secretKeyRef:
    #     name: mysqlsecret
    #     key: password
    type: "mysql"
    params:
    - key: "dsn"
      value: "root:root@tcp(mysql:3306)/foo"
  compress:
    type: "gzip"
    params:
    - key: "compressionlevel"
      value: "2"
  # encrypt:
    # type: "aesgcm" 
    # secrets:
    # - secretKeyRef:
        # name: copybirdsecret
        # key: encryptionkey
  output:
    type: "s3"
    params:
    - key: filename
      value: dump.sql
    - key: "region"
      value: "eu-central-1"
    - key: "bucket"
      value: "tzununbekov-copybird-backups"
    secrets:
    - secretKeyRef:
        name: awssecret
        key: accesskeyid
    - secretKeyRef:
        name: awssecret
        key: secretaccesskey
