apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: copybird-crd-manager-role
rules:
- apiGroups:
  - copybird.org
  resources:
  - mysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - copybird.org
  resources:
  - mysqlbackups/status
  verbs:
  - get
  - patch
  - update
