apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: copybird-crd-controller-manager-metrics-service
  namespace: copybird-crd-system
spec:
  ports:
  - port: 8443
  selector:
    control-plane: controller-manager