apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: copybird-crd-controller-manager
  namespace: copybird-crd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        env:
        - name: COPYBIRD_IMAGE
          # value: copybird/copybird:latest
          value: github.com/copybird/copybird-crd/cmd/copybird-api
        image: github.com/copybird/copybird-crd/cmd/controller
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
